import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../constants/colors';
import { jogosBaseStyles } from './JogosBase.styles';

export const adultosDeConfiancaScreenStyles = {
    ...jogosBaseStyles,
    ...StyleSheet.create({
        content: {
            padding: 20,
            paddingBottom: 40,
        },
        progressoInfo: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 8,
        },
        progressoPorcentagem: {
            fontSize: SIZES.md,
            color: COLORS.warm,
            fontWeight: 'bold',
        },
        progressoPreenchido: {
            height: '100%',
            backgroundColor: COLORS.warm,
            borderRadius: 6,
        },
        perguntaCard: {
            backgroundColor: COLORS.surface,
            borderRadius: SIZES.radiusLg,
            padding: 24,
            marginBottom: 20,
            alignItems: 'center',
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            borderLeftWidth: 4,
            borderLeftColor: COLORS.warm,
        },
        perguntaIconContainer: {
            width: 60,
            height: 60,
            borderRadius: 30,
            backgroundColor: COLORS.warm + '20',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 14,
        },
        perguntaTexto: {
            fontSize: SIZES.xl,
            color: COLORS.text,
            textAlign: 'center',
            lineHeight: 28,
            fontWeight: 'bold',
            marginBottom: 8,
        },
        multiplaTag: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: COLORS.primary + '15',
            paddingHorizontal: 14,
            paddingVertical: 6,
            borderRadius: SIZES.radiusSm,
            marginTop: 12,
            gap: 6,
        },
        multiplaTagTexto: {
            fontSize: SIZES.sm,
            color: COLORS.primary,
            fontWeight: '600',
        },
        opcaoBotao: {
            backgroundColor: COLORS.surface,
            borderRadius: SIZES.radius,
            padding: 18,
            marginBottom: 12,
            borderWidth: 2,
            borderColor: COLORS.border,
            elevation: 2,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.08,
            shadowRadius: 2,
        },
        opcaoConteudo: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        opcaoCheckbox: {
            marginRight: 14,
        },
        opcaoTexto: {
            fontSize: SIZES.lg,
            color: COLORS.text,
            flex: 1,
            lineHeight: 24,
            fontWeight: '500',
        },
        confirmarBotao: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: COLORS.primary,
            paddingVertical: 16,
            borderRadius: SIZES.radius,
            marginTop: 4,
            marginBottom: 12,
            gap: 10,
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.15,
            shadowRadius: 3,
        },
        confirmarBotaoTexto: {
            fontSize: SIZES.lg,
            fontWeight: 'bold',
            color: COLORS.textWhite,
        },
        dicaContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: COLORS.warm + '15',
            borderRadius: SIZES.radius,
            padding: 14,
            marginTop: 8,
        },
        dicaTexto: {
            fontSize: SIZES.md,
            color: COLORS.text,
            marginLeft: 10,
            flex: 1,
            lineHeight: 20,
        },
        concluidoIconContainer: {
            width: 120,
            height: 120,
            borderRadius: 60,
            backgroundColor: COLORS.warm + '20',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 24,
        },
        concluidoBotao: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: COLORS.warm,
            paddingVertical: 16,
            paddingHorizontal: 32,
            borderRadius: SIZES.radius,
            gap: 10,
        },
        concluidoBotaoTexto: {
            fontSize: SIZES.lg,
            fontWeight: 'bold',
            color: COLORS.textWhite,
        },
    }),
};