import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../constants/colors';
import { jogosBaseStyles } from './JogosBase.styles';

export const poderDoNaoScreenStyles = {
    ...jogosBaseStyles,
    ...StyleSheet.create({
        situacaoCard: {
            backgroundColor: COLORS.surface,
            borderRadius: SIZES.radiusLg,
            padding: 24,
            marginBottom: 20,
            alignItems: 'center',
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            borderLeftWidth: 4,
            borderLeftColor: COLORS.accent,
        },
        situacaoIconContainer: {
            width: 56,
            height: 56,
            borderRadius: 28,
            backgroundColor: COLORS.accent + '20',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 14,
        },
        situacaoLabel: {
            fontSize: SIZES.md,
            color: COLORS.textLight,
            fontWeight: '600',
            marginBottom: 8,
            textTransform: 'uppercase',
            letterSpacing: 1,
        },
        situacaoTexto: {
            fontSize: SIZES.xl,
            color: COLORS.text,
            textAlign: 'center',
            lineHeight: 28,
            fontWeight: '500',
        },
        instrucao: {
            fontSize: SIZES.lg,
            color: COLORS.textLight,
            textAlign: 'center',
            marginBottom: 16,
            fontWeight: '500',
        },
        opcaoBotao: {
            backgroundColor: COLORS.surface,
            borderRadius: SIZES.radius,
            padding: 18,
            marginBottom: 12,
            borderWidth: 2,
            borderColor: COLORS.border,
            elevation: 2,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.08,
            shadowRadius: 2,
        },
        opcaoSelecionada: {
            elevation: 4,
            shadowOpacity: 0.15,
        },
        opcaoConteudo: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        opcaoNumero: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: COLORS.accent + '25',
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 14,
        },
        opcaoNumeroTexto: {
            fontSize: SIZES.md,
            fontWeight: 'bold',
            color: COLORS.accent,
        },
        opcaoTexto: {
            fontSize: SIZES.lg,
            color: COLORS.text,
            flex: 1,
            lineHeight: 24,
        },
        opcaoIcone: {
            marginLeft: 10,
        },
        dicaContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: COLORS.accent + '15',
            borderRadius: SIZES.radius,
            padding: 14,
            marginTop: 8,
        },
        dicaTexto: {
            fontSize: SIZES.md,
            color: COLORS.text,
            marginLeft: 10,
            flex: 1,
            lineHeight: 20,
        },
        concluidoIconContainer: {
            width: 120,
            height: 120,
            borderRadius: 60,
            backgroundColor: COLORS.accent + '20',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 24,
        },
        concluidoBotao: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: COLORS.accent,
            paddingVertical: 16,
            paddingHorizontal: 32,
            borderRadius: SIZES.radius,
            gap: 10,
        },
        concluidoBotaoTexto: {
            fontSize: SIZES.lg,
            fontWeight: 'bold',
            color: COLORS.textWhite,
        },
    }),
};